In [1]:
import pandas as pd
import numpy as np

In [2]:
t1 = pd.read_csv('f2.csv')
t2 = pd.read_csv('f1.csv')

In [5]:
t2['win']=t2['win'].astype(int)

In [4]:
len(t2)

40769

In [6]:
t3 = pd.concat([t1,t2])

In [7]:
t3.head()

           0          1          2          3          4  win
0  Defensive  Defensive  Offensive  Defensive  Offensive    0
1  Offensive  Offensive  Defensive  Defensive  Defensive    1
2  Offensive  Offensive  Defensive  Defensive  Defensive    0
3  Offensive  Defensive  Offensive  Defensive  Offensive    1
4  Offensive  Defensive  Offensive  Defensive  Offensive    1

In [15]:
t3.iloc[0][0]

'Defensive'

In [14]:
tj_dd_w=0
tj_dd_l=0
tj_ad_w=0
tj_ad_l=0
tj_da_w=0
tj_da_l=0
tj_aa_w=0
tj_aa_l=0
mj_dd_w=0
mj_dd_l=0
mj_ad_w=0
mj_ad_l=0
mj_da_w=0
mj_da_l=0
mj_aa_w=0
mj_aa_l=0
aj_dd_w=0
aj_dd_l=0
aj_ad_w=0
aj_ad_l=0
aj_da_w=0
aj_da_l=0
aj_aa_w=0
aj_aa_l=0
sj_dd_w=0
sj_dd_l=0
sj_ad_w=0
sj_ad_l=0
sj_da_w=0
sj_da_l=0
sj_aa_w=0
sj_aa_l=0
as_dd_w=0
as_dd_l=0
as_da_w=0
as_da_l=0
as_aa_w=0
as_aa_l=0

for i in range(len(t3)):
    if t3.iloc[i][0]=='Defensive' and t3.iloc[i][1]=='Defensive':
        if t3.iloc[i][5]==1:
            tj_dd_w += 1
        else:
            tj_dd_l += 1
    if t3.iloc[i][0]=='Defensive' and t3.iloc[i][1]=='Offensive':
        if t3.iloc[i][5]==1:
            tj_da_w += 1
        else:
            tj_da_l += 1

               0          1          2          3          4  win
0      Defensive  Defensive  Offensive  Defensive  Offensive    0
1      Offensive  Offensive  Defensive  Defensive  Defensive    1
2      Offensive  Offensive  Defensive  Defensive  Defensive    0
3      Offensive  Defensive  Offensive  Defensive  Offensive    1
4      Offensive  Defensive  Offensive  Defensive  Offensive    1
5      Offensive  Offensive  Offensive  Defensive  Offensive    1
6      Defensive  Offensive  Offensive  Defensive  Offensive    1
7      Offensive  Offensive  Offensive  Defensive  Offensive    0
8      Defensive  Defensive  Offensive  Defensive  Defensive    0
9      Offensive  Offensive  Offensive  Defensive  Defensive    0
10     Offensive  Defensive  Defensive  Defensive  Offensive    1
11     Offensive  Offensive  Offensive  Defensive  Defensive    0
12     Offensive  Offensive  Offensive  Offensive  Defensive    1
13     Offensive  Offensive  Offensive  Defensive  Defensive    1
14     Offensive  Defensive  Offensive  Offensive  Defensive    1
15     Defensive  Offensive  Defensive  Defensive  Defensive    0
16     Offensive  Offensive  Offensive  Defensive  Offensive    1
17     Offensive  Defensive  Offensive  Defensive  Defensive    0
18     Defensive  Offensive  Offensive  Defensive  Defensive    0
19     Offensive  Offensive  Defensive  Defensive  Offensive    1
20     Defensive  Defensive  Offensive  Defensive  Offensive    1
21     Offensive  Offensive  Offensive  Offensive  Defensive    1
22     Offensive  Offensive  Defensive  Offensive  Defensive    1
23     Offensive  Offensive  Defensive  Defensive  Offensive    1
24     Offensive  Offensive  Defensive  Defensive  Defensive    1
25     Offensive  Offensive  Offensive  Defensive  Defensive    1
26     Offensive  Offensive  Offensive  Offensive  Defensive    1
27     Offensive  Offensive  Defensive  Defensive  Defensive    0
28     Defensive  Defensive  Offensive  Defensive  Offensive    0
29     Offensive  Defensive  Offensive  Defensive  Defensive    0
...          ...        ...        ...        ...        ...  ...
77834  Offensive  Offensive  Offensive  Defensive  Offensive    1
77835  Defensive  Offensive  Defensive  Defensive  Defensive    1
77836  Offensive  Defensive  Offensive  Defensive  Defensive    0
77837  Offensive  Offensive  Defensive  Defensive  Offensive    1
77838  Defensive  Offensive  Defensive  Defensive  Defensive    0
77839  Offensive  Offensive  Defensive  Offensive  Defensive    1
77840  Offensive  Defensive  Offensive  Offensive  Offensive    0
77841  Defensive  Offensive  Defensive  Defensive  Defensive    0
77842  Offensive  Offensive  Defensive  Offensive  Defensive    1
77843  Defensive  Offensive  Defensive  Offensive  Defensive    0
77844  Defensive  Offensive  Offensive  Defensive  Defensive    1
77845  Defensive  Offensive  Defensive  Offensive  Offensive    0
77846  Defensive  Offensive  Offensive  Defensive  Defensive    1
77847  Offensive  Offensive  Defensive  Defensive  Defensive    1
77848  Defensive  Offensive  Defensive  Offensive  Defensive    0
77849  Offensive  Defensive  Defensive  Defensive  Defensive    0
77850  Defensive  Defensive  Defensive  Defensive  Offensive    0
77851  Offensive  Offensive  Defensive  Offensive  Defensive    1
77852  Offensive  Offensive  Offensive  Defensive  Offensive    1
77853  Offensive  Defensive  Defensive  Offensive  Defensive    0
77854  Offensive  Defensive  Offensive  Defensive  Defensive    1
77855  Offensive  Offensive  Defensive  Defensive  Defensive    0
77856  Offensive  Offensive  Offensive  Defensive  Defensive    0
77857  Defensive  Offensive  Offensive  Offensive  Defensive    1
77858  Offensive  Offensive  Defensive  Offensive  Defensive    0
77859  Defensive  Offensive  Defensive  Defensive  Defensive    1
77860  Defensive  Offensive  Offensive  Offensive  Defensive    0
77861  Offensive  Offensive  Offensive  Defensive  Offensive    1
77862  Offensive  Offensive  Offensive  Offensive  Defensive    0
77863  Offensive  Offensive  Offensive  Defensive  Offensive    0

[77864 rows x 6 columns]

In [42]:
t3.groupby(['BOTTOM','BOTTOM2','WIN']).count()

                           TOP  JUNGLE  MIDDLE
BOTTOM    BOTTOM2   WIN
Defensive Defensive 0    22624   22624   22624
                    1    20259   20259   20259
          Offensive 0     7652    7652    7652
                    1     7673    7673    7673
Offensive Defensive 0     7457    7457    7457
                    1     7686    7686    7686
          Offensive 0     2110    2110    2110
                    1     2403    2403    2403

In [35]:
t3.columns = ['TOP','JUNGLE','MIDDLE','BOTTOM','BOTTOM2','WIN']

In [31]:
tj_dd = 3004/(5221+3004)
tj_do = 10215/(11514+10215)
tj_od = 5092/(6540+5092)
tj_oo = 19710/(16568+19710)

In [33]:
mj_dd = 2954/(5126+2954)
mj_do = 9841/(11133+9841)
mj_of = 5142/(6635+5142)
mj_oo = 20084/(16949+20084)

In [51]:
aj_dd = 6147/(9200+6147)
aj_do = 21785/(21785+21076)
aj_od = 1949/(2561+1949)
aj_oo = 8140/(7006+8140)

In [41]:
sj_dd = 6090/(9110+6090)
sj_do = 21855/(21855+20971)
sj_od = 2006/(2006+2651)
sj_oo = 8070/(7111+8070)

In [52]:
as_dd = 20259/(22624+20259)
as_od  = (7686+7673)/(7652+7457+7686+7673)
as_oo = 2403/(2110+2403)

In [47]:
a = dict()

In [48]:
a['tj_dd'] = tj_dd

In [49]:
a['tj_do'] = tj_do

In [53]:
a['tj_od'] = tj_od
a['tj_oo'] = tj_oo
a['mj_dd'] = mj_dd
a['mj_do'] = mj_do
a['mj_of'] = mj_of
a['mj_oo'] = mj_oo
a['aj_dd'] = aj_dd
a['aj_do'] = aj_do
a['aj_od'] = aj_od
a['aj_oo'] = aj_oo
a['sj_dd'] = sj_dd
a['sj_do'] = sj_do
a['sj_od'] = sj_od
a['sj_oo'] = sj_oo
a['as_dd'] = as_dd
a['as_od'] = as_od
a['as_oo'] = as_oo

In [62]:
win = pd.DataFrame(a.values()).T

In [64]:
win.columns = a.keys()

In [65]:
win

,tj_dd,tj_do,tj_od,tj_oo,mj_dd,mj_do,mj_of,mj_oo,aj_dd,aj_do,aj_od,aj_oo,sj_dd,sj_do,sj_od,sj_oo,as_dd,as_od,as_oo
0,0.365228,0.470109,0.437758,0.543304,0.365594,0.4692,0.436614,0.542327,0.400534,0.508271,0.432151,0.537436,0.400658,0.510321,0.430749,0.531586,0.472425,0.504103,0.532462

In [66]:
win.to_csv('승률.csv',index=False)